version: '3'
services:
  db_postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - DbData:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # open for dev purpose
    ports:
      - 5432:5432
    networks:
      - backendDjango4Vue3

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - backend-billeterie

  django4:
    image: python:3.10-bullseye
    restart: always
    volumes:
      - "../django4Backend:/django4Backend"
    working_dir: /django4Backend
    depends_on:
      - db_postgres
      - redis
    networks:
      - frontend
      - backend-billeterie

networks:
  frontend:
    name: "frontend"
  backendDjango4Vue3:
    name: "backendDjango4Vue3"

volumes:
  DbData:
